### ISSUE TITLE
[Bug]: Broken links at HowTo_ImportSBBIcons.md

### ISSUE THREAD

**Issue by Robot8A** [SchweizerischeBundesbahnen/mobile-ios-design-swiftui#100]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/SchweizerischeBundesbahnen/design_system_flutter/blob/main/Contributing.md) for this project.
- [X] I have searched the [issue tracker](https://github.com/...) for an issue that matches the one I want to file, without success.

### Bug type

Other

### It affects the following repositories

Other

### It affects the following platform (only for flutter)

None

### What happened?

The https://digital.sbb.ch/ links at https://github.com/SchweizerischeBundesbahnen/mobile-ios-design-swiftui/blob/develop/HowTo_ImportSBBIcons.md are broken

### Steps to reproduce the issue

Access https://github.com/SchweizerischeBundesbahnen/mobile-ios-design-swiftui/blob/develop/HowTo_ImportSBBIcons.md, click on a https://digital.sbb.ch/ link -> Error

**Comment by georgiosantoniadis** [comment]
I opened https://github.com/SchweizerischeBundesbahnen/mobile-ios-design-swiftui/pull/101, will be fixed as soon as it is merged.

**Comment by georgiosantoniadis** [comment]
PR merged
