### ISSUE TITLE
[Feature request]: Switch in Demo App

### ISSUE THREAD

**Issue by beatvollenwyder** [SchweizerischeBundesbahnen/mobile-ios-design-swiftui#60]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/SchweizerischeBundesbahnen/design_system_flutter/blob/main/Contributing.md) for this project.
- [X] I have searched the [issue tracker](https://github.com/orgs/...) for an issue that matches the one I want to file, without success.

### Request type

Request for a enhancement in the demo app.

### Functionality

Currently, the switch component is missing in the demo app.

### Link to design proposal file

https://www.figma.com/file/WOtLIam1xwrqcgnAITsEhV/Design-System-Mobile?node-id=36%3A16530&t=LrHaVBxIA0LeGu3s-1

**Comment by VanHoangTran** [comment]
Only needs to be added to the demo app since it was already implemented

**Comment by fleuryj** [comment]
It is in the demo, only it was called 'Toggle'. It has now been renamed to 'Switch / Toggle'.
